language: php

matrix:
  include:
    - php: 7.1
      env: CODE_COVERAGE=1
    - php: 7.0
    - php: 5.6
    - php: 5.5
      env: CS_CHECK=1
    - php: hhvm
      dist: trusty

cache:
  directories:
    - $HOME/.composer

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq postfix

install:
  - composer install
  - if [ "$CODE_COVERAGE" != 1 ]; then phpenv config-rm xdebug.ini || true; fi

before_script:
  - sudo service postfix stop
  - smtp-sink -d "%d.%H.%M.%S" localhost:2500 1000 &
  - mkdir -p build/logs
  - cp test/testbootstrap-dist.php test/testbootstrap.php
  - chmod +x test/fakesendmail.sh
  - sudo mkdir -p /var/qmail/bin
  - sudo cp test/fakesendmail.sh /var/qmail/bin/sendmail
  - sudo cp test/fakesendmail.sh /usr/sbin/sendmail
  - |
    if [[ $TRAVIS_PHP_VERSION = "hhv"* ]]; then
      echo 'sendmail_path = "/usr/sbin/sendmail -t -i "' >> /etc/hhvm/php.ini
    else
      echo 'sendmail_path = "/usr/sbin/sendmail -t -i "' > $(php --ini|grep -m 1 "ini files in:"|cut -d ":" -f 2)/sendmail.ini
    fi

script:
  - ./vendor/bin/phpunit --configuration ./travis.phpunit.xml.dist
  - if [ "$CS_CHECK" = 1 ]; then ./vendor/bin/php-cs-fixer --diff --dry-run --verbose fix; fi

after_script:
  - if [ "$CODE_COVERAGE" = 1 ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ "$CODE_COVERAGE" = 1 ]; then php ocular.phar code-coverage:upload --format=php-clover ../build/logs/clover.xml; fi
