name: Docs
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Build Docs
        uses: ./.github/actions/build-docs
      - name: Upload file artifacts
        uses: actions/upload-artifact@v1
        with:
          name: docs
          path: docs

  publish:
    name: Publish Docs
    needs: Build Docs
    runs-on: ubuntu-latest
    steps:
      - name: Download file artifacts
        uses: actions/download-artifact@v1
        with:
          name: docs
      - name: Publish Docs to gh-pages
        uses: maxheld83/ghpages@v0.2.1
        env:
          BUILD_DIR: docs/
          GH_PAT: ${{ secrets.GH_PAT }}
